wandb_version: 1

learning_rate:
  desc: null
  value: 0.5
architecture:
  desc: null
  value: FNN
dataset:
  desc: null
  value: 10 bit string
epochs:
  desc: null
  value: 5000
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707632398.938647
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
